site_name: Glint Tables
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  palette:
    scheme: slate
nav:
  - Home: index.md
  - Quick Start: quickstart.md
